language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: p8eublzRaZDD13YujCOP5s2UJRqokm4hwww8yOYTXpIoykniu+mmWllnqU0s9pJZPp6iJde7BgBbAAq+hD83sBEbYZNb/Y7ZQ8VFlkV/ILQ5oYNP6m2VdHJZeTcTW/ZDOixlUglgJMJ+5SijuEAhhcTorqtDToQoCxzNYPIi0A9UbwY1jLsaJkpYznmp3dRQS4B77el8nWzV2vm3ofMOfdMdyr4+WvFDxts2LDXLBXHjB1y4QJ30Yq61IxPWmKyc9WGFUwks1DQaLpXg8nuVO6niYmiSDSOw8L6iHi+sRf3SOpOwVXPld1aMoETC7YAxoLygclN/MNQtjSMa4QebGUp9cYgCloKXTf8k5OX4TtdkFvvxduW3ybdWxbxk3T5GSJZ+XOgwiZpv/k8xQLfDYsMHTzEaD0qFMvSksRUbqfvPeYOeVvHQzr3UTqBrTymIN4t5Evy8Xjy0qWJaFIGf+quS9qjei79jhDgQIOQ+jeZeeJIwzOKN6BXbZ/ghvv0akt/+e0M7syFWrEyzj/en8t0rKpheFXQCsr26N1KGFNaxXmrdqfw2j4HO20ZY5/ZUqNL40bdEFEfwBWQsvceD8Lod/s46OvDf9bi0frgu/qM4mPVvozugO/U0avElPDpwjulFFT4ZrHIw5VeFMTxTJhCYacmYZYNIQODMHVkMlyU=
  file:
    - "rehype-format.js"
    - "rehype-format.min.js"
  on:
    tags: true
